apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "shop-product.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ include "shop-product.fullname" . }}r